import type { ToolcraftControlSchema } from "@/toolcraft/runtime";

import {
  WEAVE_BRIGHTNESS,
  WEAVE_DENSITY,
  WEAVE_SATURATION,
  WEAVE_TARGETS,
  WEAVE_UNDERLAY,
} from "../weave/weave-params";

export const weaveSection = {
  controls: {
    density: {
      applicability: { mode: "always" },
      defaultValue: WEAVE_DENSITY.defaultValue,
      description: "Glyphs per row across the cover. Glyph count grows with the square of this value.",
      label: "Density",
      max: WEAVE_DENSITY.max,
      min: WEAVE_DENSITY.min,
      performanceReason: "Glyph count, and so layout and raster cost, grows quadratically with density.",
      performanceRole: "workload",
      sliderValueKind: "discrete",
      step: WEAVE_DENSITY.step,
      target: WEAVE_TARGETS.density,
      type: "slider",
    },
    saturation: {
      applicability: { mode: "always" },
      defaultValue: WEAVE_SATURATION.defaultValue,
      description: "Pushes each glyph's sampled cover colour away from grey.",
      label: "Saturation",
      max: WEAVE_SATURATION.max,
      min: WEAVE_SATURATION.min,
      performanceReason: "Saturation recolours every glyph without changing the glyph count.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: WEAVE_SATURATION.step,
      target: WEAVE_TARGETS.saturation,
      type: "slider",
    },
    brightness: {
      applicability: { mode: "always" },
      defaultValue: WEAVE_BRIGHTNESS.defaultValue,
      description: "Scales sampled glyph colours; 100% preserves their original brightness.",
      label: "Text brightness",
      max: WEAVE_BRIGHTNESS.max,
      min: WEAVE_BRIGHTNESS.min,
      performanceReason: "Brightness recolours every glyph without changing the glyph count or size.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: WEAVE_BRIGHTNESS.step,
      target: WEAVE_TARGETS.brightness,
      type: "slider",
      unit: "%",
    },
    font: {
      applicability: { mode: "always" },
      defaultValue: "sans",
      label: "Font",
      options: [
        { label: "Sans", value: "sans" },
        { label: "Serif", value: "serif" },
      ],
      performanceReason: "The font changes glyph widths, so the layout is recomputed once.",
      performanceRole: "responsiveness",
      target: WEAVE_TARGETS.font,
      type: "segmented",
    },
    toneSize: {
      applicability: { mode: "always" },
      defaultValue: true,
      description:
        "Bright areas get larger glyphs and dark areas smaller ones (inverted on a light background), so the cover reads from a distance.",
      label: "Tone sizing",
      performanceReason: "Tone sizing changes glyph sizes without changing the glyph count.",
      performanceRole: "responsiveness",
      target: WEAVE_TARGETS.toneSize,
      type: "switch",
    },
    compact: {
      applicability: { mode: "always" },
      defaultValue: true,
      description: "Removes punctuation and spaces so glyphs run edge to edge.",
      label: "Tight text",
      performanceReason: "Tight text changes the glyph sequence without changing the glyph count.",
      performanceRole: "responsiveness",
      target: WEAVE_TARGETS.compact,
      type: "switch",
    },
    underlay: {
      applicability: { mode: "always" },
      defaultValue: WEAVE_UNDERLAY.defaultValue,
      description: "Shows the cover itself faintly beneath the glyphs.",
      label: "Cover underlay",
      max: WEAVE_UNDERLAY.max,
      min: WEAVE_UNDERLAY.min,
      performanceReason: "Underlay opacity only re-rasterizes the existing glyph layout.",
      performanceRole: "responsiveness",
      sliderValueKind: "continuous",
      step: WEAVE_UNDERLAY.step,
      target: WEAVE_TARGETS.underlay,
      type: "slider",
      unit: "%",
    },
  } satisfies Record<string, ToolcraftControlSchema>,
  id: "weave",
  layoutGroups: [
    {
      columns: 2,
      controls: ["toneSize", "compact"],
      layout: "inline",
    },
  ] as const,
  title: "Weave",
};
