import type {
  ToolcraftComponentAcceptance,
  ToolcraftProductReadiness,
  ToolcraftTransferMode,
} from "./acceptance/types";
import { appSchema } from "./app-schema";

export { appControlSectionInventory } from "./app-control-inventory";

const persistenceSlices =
  appSchema.persistence.storage === "localStorage" ? appSchema.persistence.include : [];

const WEAVE_SPEC = "e2e/product-weave.spec.ts" as const;
const SONG_SPEC = "e2e/product-song.spec.ts" as const;
const OUTPUT_SPEC = "e2e/product-output.spec.ts" as const;

export const appTransferMode: ToolcraftTransferMode = {
  animationIntent: { mode: "none" },
  mode: "new-toolcraft-app",
  referenceInputs: [],
};

export const appProductReadiness: ToolcraftProductReadiness = {
  exportIntent: {
    image: { mode: "toolcraft-default" },
    svg: { mode: "not-requested" },
    video: { mode: "not-requested" },
  },
  interactionOwnership: [
    {
      alternative: {
        reason: "Canvas search chrome would cover the woven output and hide the result list and status.",
        surface: "canvas",
      },
      capability: "command",
      evidence: {
        detail: "The standalone version kept song search beside its settings; typing and picking need a text field and a list, not spatial feedback.",
        source: "usability-analysis",
      },
      id: "song-search",
      reason: "The controls panel owns the search field, result list and pick command that load a song.",
      surface: "panel",
      target: "song.pick",
    },
    {
      alternative: {
        reason: "Panel buttons would separate continuous panning from the spatial viewport feedback it controls.",
        surface: "panel",
      },
      capability: "direct-spatial-edit",
      evidence: {
        detail: "Usability comparison selects direct canvas dragging to inspect glyph detail across the cover.",
        source: "usability-analysis",
      },
      id: "viewport-pan",
      reason: "The canvas owns viewport panning because the gesture directly moves the visible world frame.",
      surface: "canvas",
      target: "canvas.setOffset",
    },
    {
      alternative: {
        reason: "Panel controls would duplicate runtime zoom tools and detach zoom focus from the visible canvas.",
        surface: "panel",
      },
      capability: "direct-spatial-edit",
      evidence: {
        detail: "Zooming in shows the individual lyric glyphs, which is the product's close-up view.",
        source: "usability-analysis",
      },
      id: "viewport-zoom",
      reason: "The canvas owns viewport zoom because scale and focus require immediate spatial feedback.",
      surface: "canvas",
      target: "canvas.setViewport",
    },
  ],
  mode: "product",
  productName: "Lyric Cover",
  productSummary:
    "Redraws a song's album cover out of its own lyrics: every character takes the colour of the cover beneath it, so it reads as the cover from afar and as the lyrics up close.",
  requestedBehavior:
    "Search a song or upload a cover, fetch or paste its lyrics, tune character density, colour, font and sizing, add a title caption, and export the lyric cover as an image named after the song.",
  viewInteraction: {
    mode: "non-spatial",
    reason: "The woven cover is a flat two-dimensional image with no model or camera.",
  },
};

export const appAcceptance: readonly ToolcraftComponentAcceptance[] = [
  {
    automated: true,
    automatedTestName: "interface sounds follow the job each control does",
    browser: {
      budget: "standard",
      file: "e2e/product-sound.spec.ts",
      testName: "browser acceptance: interface sounds play and the mute button silences them",
    },
    componentType: "toolbar",
    evidence: "command-side-effect",
    expectedObservable:
      "Controls play a short synthesized cue; the toolbar mute button silences every cue, keeps its state across reload, and confirms with a cue when turned back on.",
    fixture: "uploaded cover with lyrics",
    id: "interface.sound",
    kind: "runtime",
    target: "interface.sound",
    userAction: "Toggle a switch, mute, toggle again, reload, then turn sound back on.",
  },
  {
    automated: true,
    automatedTestName: "interface language preserves canonical values and translates display copy",
    browser: { budget: "standard", file: "e2e/product-interface-language.spec.ts", testName: "browser acceptance: interface language switches and survives reload" },
    componentType: "toolbar", evidence: "command-side-effect",
    expectedObservable: "Interface copy and document language switch between Chinese and English while lyrics, search language, artwork and saved values stay unchanged; the chosen language survives reload.",
    fixture: "uploaded cover, bilingual lyrics and caption",
    id: "interface.language", kind: "runtime",
    target: "interface.language", userAction: "Choose 中文, return to English, choose 中文 again and reload.",
  },
  {
    automated: true,
    automatedTestName: "declares production reload coverage for the generated product schema",
    browser: {
      budget: "extended-io",
      file: "e2e/app-persistence.spec.ts",
      testName: "browser: app restores exact canvas, values, and panel workspace slices after reload",
    },
    componentType: "persistence",
    evidence: "persistence-state",
    expectedObservable: "Canvas size, weave values and the panel workspace restore after a real reload.",
    fixture: "lyric weave persisted workspace",
    id: "persistence.reload",
    kind: "runtime",
    persistenceCoverage: "reload",
    persistenceSlices,
    target: "canvas.size.width",
    userAction: "Change Canvas width, move and collapse Controls, then reload.",
  },
  {
    automated: true,
    automatedTestName: "song search picks a song and applies cover, caption and lyrics",
    browser: {
      budget: "standard",
      file: SONG_SPEC,
      testName: "browser acceptance: song search pick weaves the picked cover",
    },
    builtInFitCheck: {
      capabilities: ["custom-value-model", "commands"],
      checkedBuiltIns: ["text", "select", "imagePicker", "fileDrop", "actions"],
      closestBuiltIn: "imagePicker",
      productObservable:
        "Picking a search result replaces the woven cover with that song's artwork and fills its caption and lyrics.",
      whyInsufficient:
        "ImagePicker chooses among a fixed authored option set; songs come from a live iTunes query the user types, and one pick must store the artwork reference and apply fetched lyrics and caption in a single command.",
    },
    componentType: "songSearch",
    customControlCoverage: "all-custom-control-behavior",
    evidence: "rendered-pixels",
    expectedObservable: "The canvas changes from empty to the picked song's woven cover with its caption.",
    fixture: "mocked iTunes search and LRCLIB lyrics",
    id: "song.search",
    interactionId: "song-search",
    kind: "control",
    target: "song.pick",
    userAction: "Type a song, choose a result with the arrow keys and press Enter.",
  },
  {
    automated: true,
    automatedTestName: "language selects the store and script applied to a pick",
    browser: {
      budget: "standard",
      file: SONG_SPEC,
      testName: "browser acceptance: language changes the picked caption script",
    },
    componentType: "segmented",
    evidence: "rendered-pixels",
    expectedObservable: "Picking the same song in 简体, 繁體 and English changes the caption drawn on the canvas.",
    fixture: "mocked TW and US store results",
    id: "song.language",
    kind: "control",
    optionCoverage: ["cn", "tw", "en"],
    target: "song.language",
    userAction: "Choose each language and pick the same song.",
  },
  {
    automated: true,
    automatedTestName: "an uploaded cover replaces the searched cover",
    browser: {
      budget: "extended-io",
      file: SONG_SPEC,
      testName: "browser acceptance: cover upload, transform, remove and reset",
    },
    componentType: "fileDrop",
    evidence: "media-lifecycle",
    expectedObservable:
      "Uploading a cover weaves it uncropped at its own aspect ratio, rotate and flip change the woven pixels, and remove or reset clears it.",
    fixture: "landscape PNG cover",
    id: "source.cover",
    kind: "control",
    mediaLifecycleCoverage: ["upload", "rotate", "flip", "transform-output", "remove", "reset"],
    target: "source.cover",
    userAction: "Upload a cover, rotate and flip it, remove it, upload again and reset controls.",
  },
  {
    automated: true,
    automatedTestName: "lyrics become the glyph sequence",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: editing lyrics re-weaves the glyphs",
    },
    componentType: "code",
    evidence: "rendered-pixels",
    expectedObservable: "Replacing the lyrics changes the glyphs drawn across the cover.",
    fixture: "uploaded cover with lyrics",
    id: "song.lyrics",
    kind: "control",
    target: "song.lyrics",
    userAction: "Type different lyrics.",
  },
  {
    automated: true,
    automatedTestName: "density sets glyphs per row",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: density drag changes glyph count live",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Density changes the glyph grid and pixels during the drag.",
    fixture: "uploaded cover with lyrics",
    id: "weave.density",
    kind: "control",
    target: "weave.density",
    userAction: "Drag the Density slider.",
  },
  {
    automated: true,
    automatedTestName: "saturation pushes glyph colours away from grey",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: saturation drag recolours glyphs live",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Saturation changes glyph colours during the drag.",
    fixture: "uploaded cover with lyrics",
    id: "weave.saturation",
    kind: "control",
    target: "weave.saturation",
    userAction: "Drag the Saturation slider.",
  },
  {
    automated: true,
    automatedTestName: "brightness scales glyph colours without changing glyph sizes",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: brightness drag brightens glyphs live",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Text brightness changes glyph luminance during the drag while preserving glyph size.",
    fixture: "uploaded cover with lyrics",
    id: "weave.brightness",
    kind: "control",
    target: "weave.brightness",
    userAction: "Drag the Text brightness slider.",
  },
  {
    automated: true,
    automatedTestName: "font switches the glyph family",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: font options change glyph shapes",
    },
    componentType: "segmented",
    evidence: "rendered-pixels",
    expectedObservable: "Sans and Serif draw different glyph shapes.",
    fixture: "uploaded cover with lyrics",
    id: "weave.font",
    kind: "control",
    optionCoverage: ["sans", "serif"],
    target: "weave.font",
    userAction: "Choose Serif, then Sans.",
  },
  {
    automated: true,
    automatedTestName: "tone sizing scales glyphs with cover brightness",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: tone sizing changes glyph sizes",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Turning Tone sizing off draws every glyph at the full cell size.",
    fixture: "uploaded cover with lyrics",
    id: "weave.toneSize",
    kind: "control",
    target: "weave.toneSize",
    userAction: "Turn Tone sizing off and on.",
  },
  {
    automated: true,
    automatedTestName: "tight text removes punctuation from the glyph run",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: tight text changes the glyph run",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Turning Tight text off keeps punctuation and line separators in the glyph run.",
    fixture: "uploaded cover with punctuated lyrics",
    id: "weave.compact",
    kind: "control",
    target: "weave.compact",
    userAction: "Turn Tight text off and on.",
  },
  {
    automated: true,
    automatedTestName: "cover underlay shows the cover beneath the glyphs",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: cover underlay drag shows the cover live",
    },
    componentType: "slider",
    evidence: "rendered-pixels",
    expectedObservable: "Dragging Cover underlay brightens the gaps between glyphs during the drag.",
    fixture: "uploaded cover with lyrics",
    id: "weave.underlay",
    kind: "control",
    target: "weave.underlay",
    userAction: "Drag the Cover underlay slider.",
  },
  {
    automated: true,
    automatedTestName: "caption switch adds and removes the title strip",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: caption switch toggles the strip",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable: "Turning Caption off removes the title strip and shows glyphs to the bottom edge.",
    fixture: "uploaded cover with lyrics, title and artist",
    id: "caption.enabled",
    kind: "control",
    target: "caption.enabled",
    userAction: "Turn Caption off and on.",
  },
  {
    automated: true,
    automatedTestName: "caption title is drawn in the strip",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: caption title changes the strip",
    },
    componentType: "text",
    evidence: "rendered-pixels",
    expectedObservable: "Editing Title changes the text in the caption strip.",
    fixture: "uploaded cover with lyrics",
    id: "caption.title",
    kind: "control",
    target: "caption.title",
    userAction: "Type a title.",
  },
  {
    automated: true,
    automatedTestName: "caption artist is drawn in the strip",
    browser: {
      budget: "standard",
      file: WEAVE_SPEC,
      testName: "browser acceptance: caption artist changes the strip",
    },
    componentType: "text",
    evidence: "rendered-pixels",
    expectedObservable: "Editing Artist changes the text in the caption strip.",
    fixture: "uploaded cover with lyrics",
    id: "caption.artist",
    kind: "control",
    target: "caption.artist",
    userAction: "Type an artist.",
  },
  {
    automated: true,
    automatedTestName: "soft fade switches the caption between a solid strip and a faded edge",
    browser: {
      budget: "standard",
      file: SONG_SPEC,
      testName: "browser acceptance: soft fade replaces the solid caption strip",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Off, the weave stops at a solid strip under the caption; on, the glyph rows above the caption grow fainter instead.",
    fixture: "uploaded cover with lyrics and a title",
    id: "caption.fade",
    kind: "control",
    target: "caption.fade",
    userAction: "Turn Soft fade on and off.",
  },
  {
    automated: true,
    automatedTestName: "background inclusion controls preview and PNG transparency",
    backgroundOutputCoverage: [
      "finite-media-stacking",
      "image-transparent-when-excluded",
      "preview-hidden-when-excluded",
    ],
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: background inclusion controls preview and PNG alpha",
    },
    componentType: "switch",
    evidence: "rendered-pixels",
    expectedObservable:
      "Turning Background off removes the preview fill behind the glyphs and exports a transparent PNG.",
    fixture: "woven cover with background",
    id: "output.background-inclusion",
    kind: "control",
    target: "export.includeBackground",
    userAction: "Toggle Background and compare preview and PNG alpha.",
  },
  {
    automated: true,
    automatedTestName: "light background inverts tone sizing",
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: background colour reaches preview and export",
    },
    componentType: "color",
    evidence: "exported-bytes",
    expectedObservable: "The selected Background colour appears behind the glyphs in the exported image.",
    fixture: "woven cover with background",
    id: "output.background-color",
    kind: "control",
    target: "appearance.background",
    userAction: "Change Background color and inspect decoded export pixels.",
  },
  {
    automated: true,
    automatedTestName: "image format options remain selectable",
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: image format selects the exported encoding",
    },
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exporting with PNG and then JPG downloads a PNG and a JPEG of the woven cover.",
    fixture: "woven cover image formats",
    id: "output.image-format",
    kind: "control",
    optionCoverage: ["png", "jpg"],
    target: "export.image.format",
    userAction: "Select PNG and JPG and export each.",
  },
  {
    automated: true,
    automatedTestName: "image resolution options remain selectable",
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: image resolution selects the exported size",
    },
    componentType: "select",
    evidence: "exported-bytes",
    expectedObservable: "Exporting at 2K, 4K and 8K downloads images with 2048, 4096 and 8192 pixel long edges.",
    fixture: "woven cover image resolutions",
    id: "output.image-resolution",
    kind: "control",
    optionCoverage: ["2k", "4k", "8k"],
    target: "export.image.resolution",
    userAction: "Select 2K, 4K and 8K and export each.",
  },
  {
    actionCoverage: ["export.png"],
    automated: true,
    automatedTestName: "export re-weaves the frame at export resolution",
    browser: {
      budget: "extended-io",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: image export contains the woven cover",
    },
    componentType: "panelActions",
    evidence: "exported-bytes",
    exportArtifactCoverage: "all-required-image-export-behavior",
    expectedObservable: "The exported image has the selected size and contains the woven glyph colours.",
    fixture: "woven cover export",
    id: "output.image-export",
    kind: "control",
    target: "actions.output",
    userAction: "Export PNG and JPG at 2K, 4K and 8K and inspect decoded pixels.",
  },
  {
    automated: true,
    automatedTestName: "weave canvas uses the selected backing pixels",
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: weave canvas backs the selected render scale",
    },
    componentType: "canvas",
    evidence: "rendered-pixels",
    expectedObservable: "The weave canvas backing equals CSS size × device pixel ratio × Resolution scale.",
    fixture: "woven cover at render scale 1 and 2",
    id: "output.render-scale",
    kind: "runtime",
    renderScaleCoverage: { kind: "selected-backing-pixels", states: ["interaction", "steady"] },
    target: "canvas.renderScale",
    userAction: "Change Resolution scale and inspect the canvas backing during and after interaction.",
  },
  {
    automated: true,
    automatedTestName: "canvas frame follows the cover and the caption sits inside it",
    browser: {
      budget: "standard",
      file: SONG_SPEC,
      testName: "browser acceptance: canvas follows the cover ratio and the caption sits inside it",
    },
    canvasSizingCoverage: "intrinsic-media-size",
    componentType: "canvas",
    evidence: "rendered-pixels",
    expectedObservable:
      "The canvas takes the cover's aspect ratio without cropping it; a caption keeps that ratio and takes a strip along the cover's bottom edge; there are no manual size controls.",
    fixture: "landscape PNG cover with lyrics",
    id: "output.cover-frame",
    kind: "runtime",
    target: "source.cover",
    userAction: "Upload a landscape cover, then type a caption title.",
  },
  {
    automated: true,
    automatedTestName: "canvas pan moves the woven frame",
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: canvas pan moves the viewport",
    },
    componentType: "canvas viewport",
    evidence: "viewport-side-effect",
    expectedObservable: "Dragging the canvas changes the viewport offset without changing the output size.",
    fixture: "woven cover viewport",
    id: "output.viewport-pan",
    interactionId: "viewport-pan",
    kind: "runtime",
    target: "canvas.setOffset",
    userAction: "Drag the canvas.",
  },
  {
    automated: true,
    automatedTestName: "canvas zoom scales the woven frame",
    browser: {
      budget: "standard",
      file: OUTPUT_SPEC,
      testName: "browser acceptance: canvas zoom changes the viewport",
    },
    componentType: "canvas viewport",
    evidence: "viewport-side-effect",
    expectedObservable: "Zooming changes the viewport scale without changing the output size.",
    fixture: "woven cover viewport",
    id: "output.viewport-zoom",
    interactionId: "viewport-zoom",
    kind: "runtime",
    target: "canvas.setViewport",
    userAction: "Zoom in with the toolbar.",
  },
];
